name: crosscheck
'on':
  workflow_dispatch: null
  schedule:
    - cron: 0 3 * * 5
    
jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
      - name: Clone Repo
        uses: "actions/checkout@v2.3.4"
        
      - name: Process
        run: |
          (
          sudo chmod 755 main.sh
          sudo bash main.sh
          )

      - name: Commit & Push
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
